# Gateway Multicaster Configuration for go-breaker

## Paste this configuration in the breakers.toml file
# GET Endpoints

[[endpoints]]
name = "Get Breaker Status"
path = "/breaker/enabled"
method = "GET"
description = "Get the current status of the breaker"

[[endpoints]]
name = "Get Memory Threshold"
path = "/breaker/memory"
method = "GET"
description = "Get the current memory threshold percentage"

[[endpoints]]
name = "Get Latency Threshold"
path = "/breaker/latency"
method = "GET"
description = "Get the current latency threshold in milliseconds"

[[endpoints]]
name = "Get Latency Window Size"
path = "/breaker/latency_window_size"
method = "GET"
description = "Get the current latency window size"

[[endpoints]]
name = "Get Percentile"
path = "/breaker/percentile"
method = "GET"
description = "Get the current percentile value used for latency calculation"

[[endpoints]]
name = "Get Wait Time"
path = "/breaker/wait"
method = "GET"
description = "Get the current wait time in seconds before retrying after circuit is open"

[[endpoints]]
name = "Test Endpoint"
path = "/test"
method = "GET"
description = "Test endpoint that uses the breaker for protection"

[[endpoints]]
name = "Get trend analysis status"
path = "/breaker/trend_analysis"
method = "GET"
description = "Get trend analysis status"

# POST Endpoints

[[endpoints]]
name = "Set Memory Threshold"
path = "/breaker/set_memory"
method = "POST"
description = "Set the memory threshold percentage"

[endpoints.body]
content_type = "application/json"
schema = '''
{
  "threshold": "number"
}
'''

[[endpoints]]
name = "Set Latency Threshold"
path = "/breaker/set_latency"
method = "POST"
description = "Set the latency threshold in milliseconds"

[endpoints.body]
content_type = "application/json"
schema = '''
{
  "threshold": "number"
}
'''

[[endpoints]]
name = "Set Latency Window Size"
path = "/breaker/set_latency_window_size"
method = "POST"
description = "Set the latency window size"

[endpoints.body]
content_type = "application/json"
schema = '''
{
  "size": "number"
}
'''

[[endpoints]]
name = "Set Percentile"
path = "/breaker/set_percentile"
method = "POST"
description = "Set the percentile value for latency calculation"

[endpoints.body]
content_type = "application/json"
schema = '''
{
  "percentile": "number"
}
'''

[[endpoints]]
name = "Set Wait Time"
path = "/breaker/set_wait"
method = "POST"
description = "Set the wait time in seconds before retrying after circuit is open"

[endpoints.body]
content_type = "application/json"
schema = '''
{
  "wait_time": "number"
}
'''

[[endpoints]]
name = "Set Delay"
path = "/set_delay"
method = "POST"
description = "Set the delay for the test endpoint in milliseconds"

[endpoints.body]
content_type = "application/json"
schema = '''
{
  "delay": "string"
}
'''

[[endpoints]]
name = "Set trend analysis status"
path = "/breaker/set_trend_analysis"
method = "POST"
description = "Set trend analysis status"

[endpoints.body]
content_type = "application/json"
schema = '''
{
  "enabled": "boolean",
}
'''

[[endpoints]]
name = "Enable Breaker"
path = "/breaker/enable"
method = "POST"
description =  "Enable the breaker"

[[endpoints]]
name = "Disable Breaker"
path = "/breaker/disable"
method = "POST"
description =  "Disable the breaker"

[[endpoints]]
name = "Reset Breaker"
path = "/breaker/reset"
method = "POST"
description =  "Reset the breaker"
[endpoints.body]
content_type = "application/json"
schema = '''
{
  "confirm": "boolean"
}
'''

[endpoints.body]
content_type = "application/json"
schema = '''
{
  "confirm": "boolean"
}
'''

[[endpoints]]
name = "Get Circuit Breaker Status"
path = "/breaker/status"
method = "GET"
description =  "Get the current status of the breaker"
